version: "3.8"

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      MONGODB_URI: mongodb://shared-mongodb:27017/user-management
      REDIS_URL: redis://shared-redis:6379
      REDIS_HOST: shared-redis
      REDIS_PORT: 6379
      ELASTICSEARCH_URL: http://shared-elasticsearch:9200
      JWT_SECRET: ${JWT_SECRET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL}
    networks:
      - shared-backend

networks:
  shared-backend:
