version: "3.8"

services:
  user-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: user-api-app
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      MONGODB_URI: mongodb://shared-mongodb:27017/user-management
      REDIS_URL: redis://shared-redis:6379
      REDIS_HOST: shared-redis
      REDIS_PORT: 6379
      ELASTICSEARCH_URL: http://shared-elasticsearch:9200
      JWT_SECRET: ${JWT_SECRET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL}
      PORT: 3002
    networks:
      - shared-backend
    depends_on:
      - shared-mongodb
      - shared-redis
      - shared-elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    entrypoint: ["./wait-for-all.sh", "node", "dist/main.js"]

networks:
  shared-backend:
    external: true
